# Generated by Django 3.2.6 on 2023-09-09 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_triedpass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TriedPass',
        ),
    ]
