# Generated by Django 3.2.6 on 2023-09-13 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0007_delete_triedpass'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='date_attempted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='results',
            field=models.JSONField(null=True),
        ),
    ]
