# Generated by Django 3.2.6 on 2023-09-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0010_result_resultsfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='passed',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='progresschartid',
            field=models.IntegerField(null=True),
        ),
    ]
